name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: readoelf
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Setup build directory
      run: |
        mkdir build

    - name: Build windows version
      run: |
        cd cmd/readoelf
        GOOS=windows go build -o ../../build/readoelf.exe

    - name: Build linux version
      run: |
        cd cmd/readoelf
        go build -o ../../build/readoelf
        
    - name: Build macOS version
      run: |
        cd cmd/readoelf
        GOOS=darwin go build -o ../../build/readoelf-macos

    - name: Upload windows version
      uses: actions/upload-artifact@v2
      with:
        name: readoelf.exe
        path: build/readoelf.exe

    - name: Upload linux version
      uses: actions/upload-artifact@v2
      with:
        name: readoelf
        path: build/readoelf

    - name: Upload macOS version
      uses: actions/upload-artifact@v2
      with:
        name: readoelf-macos
        path: build/readoelf-macos
